language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install liblapack-dev gfortran libblas-dev

  # Miniconda install from https://gist.github.com/dan-blanchard/7045057
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  # Create anaconda env for pip
  - conda update --yes conda
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - source activate condaenv
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy pymc
  - pip install -r requirements.txt
  - python setup.py sdist install

script: make test
