BillMurray = """DDDDDDDDDDDDDDDDDDDDDDDDDDZD8DDDDDZZZDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDNNNDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDZZ8ZZZZ$DDDDDDDZZZDDDDDDDDDDDDDDDDDDDDDDDDDDNDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDZD8Z$DDZZD8ZDDDDDDZOZZZZZDZZDDDDDDDDDDDDDDDNDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDZZZDZDDDDDDDDDDDDDDD8=~=ZZ+ZDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDD$Z8DDD~8D=~~~~~~~~~~~$~~..IZZ+8DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDN8Z88DDD:~~...............D8~...DDZ8DZDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDD8ZNDDDDD~ ...................,.....:DDZZDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDOZZODDDDD7............................~..DZZZ8ZDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDNDZ8ZNDD................................=.~DD8ZNDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDZ$ZNDD..................................~~~IDD$ZDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDZZ~=DD7~...................................~~~~ZDZZNDDDDDDDDDDDDDDDDDD
DDDDDDDDDZZ~~~D~~~~~.................................~~~~~~ZZZDDDDDDDDDDDDDDDDDD
DDDDDDDDDD$~~=~~~~~~..................................~~~~=.~.ZDDDDDDDDDDDDDDDDD
DDDDDDDDDZ?$:~~~~~~~....................................~~~Z..D8DDDDDDDDDDDDDDDD
DDDDDDDDD=Z..~~~~~~~...............................~~....~~ZZ..8DDDDDDDDDDDDDDDD
DDDDDDDD~....~~~~~~~......................................~$Z?.. DDDDDDDDDDDDDDD
DDDDDD$~....Z~~~~~~~......................................:$ZZ.,~DDDDDDDDDDDDDDD
DDDDDDZ ~~~$ZZ+~~~~~...........................+ZZ$ZZZZ ...~ZZZ.~DDDDDDDDDDDNDDD
DDDDDDZ.~~,.$$~~~~~~..........  ...............ZDDDDDDDDZ~.~~8Z~$Z8DDDDDDDDDDDDD
DDDDDZZ7=,.:Z$Z~~~~........IZDDDZ~............?ZDDOZ$ZZZDZ$~~ZNZ~ZZDDDDDDDDDDDDD
DDDDDOZZ=:.Z~ZZ~~~~~....$8DDDDDDDZ$~.........ZDDZ ......$~DZZODZ~ZDNDNDDDNDDDDDD
DDDDDDZZZZ ~ZODZ~~~~..ZDDDZ?...$ZDDD$$......:DZ~~.=ZZ,. .~~DDDDO$NNDDDDDDDNDDDDD
DDDNDDZNDZ~~ODDZ=~~~~:ZD$........  8DZ .....?Z~~Z~~DDD8=DDDDDDDDD.DDDDDDDDDDDDDN
DDDDDDDDZZ~7DDDZZ~~~~~DZ...~DD88D=...DZ ....,~.Z=DDDDD=IDDDDZZZZO DDDDDDDDDDDDDD
DDDDDDDDZO$ZDDNZ:~~$DNZZZ~8.DD8D:..~... .......... ,~~..8DD~..$ZD...,ODDDDDDDDDD
DDDDDDDDDDZZDDDZZ~~8DZZZDDDDDDD$..D .....................~~~...ZN..8D8DDDDDDDDDD
DDDDDDDDDDZZDDDZZ~~~ZZZDDDDDD~~.......~........~....~~~~~~,.....$.DDD~~DDDDDDDDD
DDDDDDDDDDZZDDDZ~~~~ZI.Z:.Z$Z, .................~...............+DZZ7.~DDDDDDDDD
DDDDDDDDDDDZZDDZ~~..........,~~.................:~.............,OZ~~$ ~=DDDDDDDD
DDDDDDD~~~DDDDDZ~~...................$ZZ,.......ZZ.............=D8~~+$:~DDDDDDDD
DDDDDDDOZZZDZDD$~~...................~ .ZZ7 ...ZD.............~ZDD~, Z.~DDDDDDDD
DDDDDDDDDDDZD~ODZ~~......................DDDDDDDDDD~,.........ZZDD~..Z.~DDDDDDDD
DDDDDDD.Z~ZDD~IDD$Z~,................$$ODDDDDDDDDDD..,........ZZDDZ. $.~DDDDDDDD
DDDDDDD.Z.=DD+.DDDDZ$................DDD8DDDDDDD=~ O.........~ZZDDZ.,Z.DDDDDDDDD
DDDDDDD.Z..~D$.8DDZDZ$,................D..,:DDDZ?I .........~ZZ~DDZ~~..DDDDDDDDD
DDDDDDD.Z...~Z.ZDDDZ8DDZZ..............,.,..DDDZ8.Z:~.....~~~$Z~DDZ...8DDDDDDDDD
DDDDDDD.Z....8=.ZDDZ? ZOZZ..............Z+DDDDDDDZDDD$DD...~~ZZ~D8....DDDDDDDDDD
DDDDDDDDIZ...~D.ZIDDZ...ZZZ.............OD$DDDDDDDDDDDDD8..~OZ~~DZ?..DDDDDDDDDDD
DDDDDDDD. D8 .D...ZDZZ....Z:.........ZOODDD....... ODDDDD...,=D8DZZDDDDDDDDDDDDD
DDDDDDDDD..~~DDD..Z $Z$..:~~....Z,D$Z8DD$~~~?$Z+ZZ8D...DD......ZZZZDDDDDDDDDDDDD
DDDDDDDDDD~...ZDD...ZDZ:.........DDDNO~~ZZ$ZZ............7...~..ZZZDDDDDDDDDDDDD
DDDDDDDDDDD$ZZZDD...ZIZ$.~. ...........................~::......ZDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDD8.~7 ...~~..:......................~....,.. I$ZDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDZZ...~: ~.................~~............~.~=8DDDDDDDDDDDDNDDD
DDDDDDDDDDDDDDDDDDDDD$Z=~$~.,,.~.~........, .......,~.+$....~7ZODDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDZ$~~~...~~~.~.........:....:..:Z:,~~~ONDDDDDDDDDDDDDNDDD
DDDDDDDDDDDDDDDDDDDDDDDDZZ+?.....~,...~.......~~..~..~~ZZ$~Z8DDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDZZ$~.~7~ZZ.~~~.....~+=~7~ZZZZN8NDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDOZZZDDD~=ZZ$ZODZ8$ZZZ8DNDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDNDDD
DDDDDDDDDDDDDDDDDDDDDOODDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDNDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDD8$ZZZDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDD7.OZZZ$DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDD..8ZZZZZDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDD... DZZZZZDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD?DDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDD.....DZZZZZ$DDDDDDDDNDDDDDDDDDDDDDDDDDDDDDD.DDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDD......ZZZZZZ$DDDDDDDDDDDDDDDDDDDDDNDDDDDD?.DDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDD........,ZZZZZODDDDDDDDDDDNODD8ODDDDDDDD..NDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDD8..........~ZZZZZODDDDDDDDOZZZZZZDDDDDDO...NDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDD ...........$ZZZZZZZDDDZZZZZZZ$DDDD8N....NDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDD............. $ZZZZZZZZZZZZZZDDDDZZ .....DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDD:..............ZZZZZZZZZZZDDDDDZZ$......DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDI...............+$ZZZZZZZDDZZZZZ.......IDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDD$................,ZZZZZZZZZZZZ........ NDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDD..................$ZZZZZZZZ..........:DDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDD8...................ZZZZZZ............DDDDDNNNNDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDD8....................ZZ?..............DDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD....................................DDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD...................8DDO.............DDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.................?DDDD.............DDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDNDDD................DDDDDD$...........8DDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDNDDDDDDDDDDDDDD..............DDDDDDDDD.......... DDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD...........~DDDDDDDDDDDI.........DDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.........DDDDDDDDDDDDDDD........8DDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD......?DDDDDDDDDDDDDDDDDD.......DDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDO... 8DDDDDDDDDDDDDDDDDDDDD:....DDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD..DDDDDDDDDDDDDDDDDDDDDDDDDDD..DDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
"""

print BillMurray
